language: node_js
node_js:
  - '8'
  - '10'
  - '11'
sudo: false
cache: yarn
before_install:
  - npm install --global codecov coveralls
script:
  - yarn test
after_script:
  - cat ./coverage/lcov.info | coveralls
  # - nyc report --reporter=text-lcov > coverage.lcov && codecov
